### ISSUE TITLE
ControlType: PaneControl    ClassName: SafeEdit 如何赋值

### ISSUE THREAD

**Issue by sjcfz** [yinkaisheng/Python-UIAutomation-for-Windows#72]
ControlType: PaneControl    ClassName: SafeEdit 如何赋值，能根据PaneControl和foundIndex获取到，能设置焦点，但不知道怎么赋值，谢谢！

**Comment by yinkaisheng** [comment]
控件是PaneControl不是Edit, 可能不支持赋值，可通过模拟点击，发送按键 ctr+a, ctr+c,  ctrl+v赋值

**Comment by sjcfz** [comment]
panePwd = paneTdx.PaneControl(Depth=1,foundIndex=2)
    auto.SetClipboardText('123456')
    panePwd.Click()
    time.sleep(0.1)
    panePwd.SendKeys('{Ctrl}a', waitTime = 0.1)
    panePwd.SendKeys('{Ctrl}v', waitTime = 0.1)
还是不行，点击光标进去了，但没有赋值。另外这个组件是可以点击键盘输入的，但是用咱们的组件赋值不了。

**Comment by sjcfz** [comment]
我引入另一python组件pynput模拟输入内容是可以的，不知道咱们的组件哪里有问题，帮忙看下哈

**Comment by yinkaisheng** [comment]
这是什么软件？

**Comment by cfz1025** [comment]
我用的是东方通达信终端的“交易密码”输入

**Comment by sjcfz** [comment]
我用的是东方通达信终端的“交易密码”输入

**Comment by sjcfz** [comment]
大佬，有没有qq群，这样大家向你请教比较方便

**Comment by yinkaisheng** [comment]
分析了一下，它这个是安全密码输入框，做了一些限制，使用pynput在那个输入框打字
pynput.keyboard.Controller().type('abc123ABC!@')
只有abc123能打上去，大写的字母和有的特殊字符打不上去，Ctrl+C, Ctrl+V也禁用了。
我的uiautomation.SendKeys('abc123ABC')，都打不上去，是因为我实现的打字和pynput的打字稍微有部分不同。
但是用我的另一个方法uiautomation.SendKey(int)分开打每一个字符是可以打上去的，这样调用稍微麻烦点。

我的SendKeys是不受输入法影响的，比如打开记事本，并切换到中文输入法，用代码打字，这时如果用
pynput.keyboard.Controller().type('nihao ')，实际打上去的是汉字“你好”，因为当前在中文输入法模式。
而用uiautomation.SendKeys('nihao ')，在中文输入法模式下打的字还是'nihao '，而不会变成中文“你好”。
但这种模式在那个密码控件上不能打字，在其它的标准输入Edit上是能打字的。

更新代码，现在我在SendKeys里加了一个参数charMode，支持切换成pynput那样的方式打字，如果要打大写和特殊字符的话要加些特殊按键。
比如uiautomation.SendKeys('ab12{Shift}a{Shift}b{Shift}1{Shift}2', charMode=False)，可以在那个密码控件上面打字了，打出的字是“ab12AB!@”，后四个字母是按住Shift键打出大写和特殊字符。

**Comment by sjcfz** [comment]
谢谢支持，另外发现执行每个操作时间有点长，很多操作的waitTime应该在0.01秒即可，建议开放全局参数，增加初始化配置函数，每个操作都设置waitTime等参数比较麻烦，这样使用者可以根据需要在开始一次指定，需要调整的时候再设置时间

**Comment by Harry2010410** [comment]
@yinkaisheng @sjcfz    大佬，帮忙看下这个问题呗，对EditControl做了简单封装，在使用SendKeys方法时，一直报这个错，请大佬有空帮忙指点一下多谢！
 File "D:\Workspace\Automan\src\Action.py", line 235, in sendKeys
    edit.SendKeys(s, charMode=False)
  File "C:\Python37\lib\site-packages\uiautomation\uiautomation.py", line 6137, in SendKeys
    SendKeys(text, interval, waitTime, charMode)
  File "C:\Python37\lib\site-packages\uiautomation\uiautomation.py", line 2641, in SendKeys
    SendUnicodeChar(key[0], charMode)
  File "C:\Python37\lib\site-packages\uiautomation\uiautomation.py", line 2451, in SendUnicodeChar
    KeyboardInput(vk, scan, flag | KeyboardEventFlag.KeyUp))
  File "C:\Python37\lib\site-packages\uiautomation\uiautomation.py", line 2418, in SendInput
    ret = ctypes.windll.user32.SendInput(1, ctypes.byref(ip), cbSize)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: **expected LP_INPUT instance instead of pointer to INPUT**

**Comment by yinkaisheng** [comment]
@Harry2010410  #65
